language: node_js
cache: npm
node_js:
  - '8'
  - '10'
  - 'node'
script:
  - npm run format-check
  - npm run lint-check
  - npm test
  - npm run build
after_script:
  - npm run coveralls
